language: java
jdk: oraclejdk8
sudo: false
before_install:
   mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_deply:
   cf login -u $BLUEMIX_USER -o $BLUEMIX_ORG
script:
   mvn test -B
language: java
git:
  depth: 1
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORG
  space: $BLUEMIX_SPACE
  manifest: manifest.yml
  app_name: ibmcloudapp
  region: eu-gb
  api: https://api.eu-gb.bluemix.net
  skip_cleanup: true
